/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Feb 3, 2011, 11:05:53 PM
 */

package smartboardgui;

import WSClient.sessions.Sessions;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.naming.Binding;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.application.Action;
import org.json.me.JSONException;
import org.pushingpixels.substance.api.inputmaps.SubstanceInputMapUtilities;

/**
 *
 * @author HitchX
 */
public class MainForm extends javax.swing.JFrame {
    private int _userID;
    /** Creates new form MainForm */





    public MainForm() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dimensions = toolkit.getScreenSize();
        int x =(int) dimensions.getWidth();
        int y =(int) dimensions.getHeight();
        this.setBounds(x/2 - this.getWidth()/2, y/2 - this.getHeight()/2, this.getWidth(), this.getHeight());
        this.setResizable(false);
    }

    public void setSessionId(int id){
        _userID = id;

    }
    public void getAllSessions(boolean onlyMy) throws JSONException{
        if(onlyMy){
        tabMySessions.getSessions(_userID,0);
        }else{
        tabMySessions.getSessions(_userID,0);
        tabFriendsSessions.getSessions(_userID, 1);
        tabOtherSessions.getSessions(_userID, 2);
        }
 
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Tabs = new javax.swing.JTabbedPane();
        tabMySessions = new smartboardgui.TabView();
        tabFriendsSessions = new smartboardgui.TabView();
        tabOtherSessions = new smartboardgui.TabView();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNewSession = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mExit = new javax.swing.JMenuItem();

        jSeparator1.setName("jSeparator1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smartboardgui.SmartBoardGUIApp.class).getContext().getResourceMap(MainForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        Tabs.setName("Tabs"); // NOI18N

        tabMySessions.setName("tabMySessions"); // NOI18N
        Tabs.addTab(resourceMap.getString("tabMySessions.TabConstraints.tabTitle"), tabMySessions); // NOI18N

        tabFriendsSessions.setName("tabFriendsSessions"); // NOI18N
        Tabs.addTab(resourceMap.getString("tabFriendsSessions.TabConstraints.tabTitle"), tabFriendsSessions); // NOI18N

        tabOtherSessions.setName("tabOtherSessions"); // NOI18N
        Tabs.addTab(resourceMap.getString("tabOtherSessions.TabConstraints.tabTitle"), tabOtherSessions); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(smartboardgui.SmartBoardGUIApp.class).getContext().getActionMap(MainForm.class, this);
        mNewSession.setAction(actionMap.get("newSession")); // NOI18N
        mNewSession.setText(resourceMap.getString("mNewSession.text")); // NOI18N
        mNewSession.setName("mNewSession"); // NOI18N
        jMenu1.add(mNewSession);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu1.add(jSeparator2);

        mExit.setAction(actionMap.get("quit")); // NOI18N
        mExit.setText(resourceMap.getString("mExit.text")); // NOI18N
        mExit.setName("mExit"); // NOI18N
        mExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mExitMouseClicked(evt);
            }
        });
        jMenu1.add(mExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mExitMouseClicked
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mExitMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    @Action
    public void newSession() throws JSONException {
     NewSessionView view = new NewSessionView(this,true,_userID);
     view.setResizable(false);
     view.setTitle("New Session");
     view.setLocationRelativeTo(this);
     view.setVisible(true);
     getAllSessions(true);
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mNewSession;
    private smartboardgui.TabView tabFriendsSessions;
    private smartboardgui.TabView tabMySessions;
    private smartboardgui.TabView tabOtherSessions;
    // End of variables declaration//GEN-END:variables

}
